import React from 'react';
import { AuthProvider } from "../context/AuthContext";
import { FavoritesProvider } from "../context/FavoritesContext";
import NavBar from "../components/NavBar/NavBar";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { FaFacebookF, FaTwitter, FaInstagram, FaLinkedin, FaYoutube, FaLifeRing, FaRegCopyright } from "react-icons/fa";
import { IoLayers } from "react-icons/io5";

// Définition des polices
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = { title: "Next.js Project", description: "Generated by create next app" };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <FavoritesProvider>
            <NavBar />
            {children}

            <section className="w-full h-80 bg-white flex justify-center items-center">
              <div className="w-2/5 h-3/5 flex justify-center items-center rounded shadow-md">
                <div className="w-2/5 h-5/6 pl-2">
                  <img className="w-full h-full rounded" src="/bookTable.jpg" alt="Books table" />
                </div>
                <div className="w-3/5 h-5/6 flex flex-col gap-3 pl-5 py-1">
                  <h1 className="text-3xl font-bold">Join Our Community</h1>
                  <p>Sign up & get 10% off your first books.</p>
                  <div className="w-full">
                    <input className="shadow-md w-3/5 p-1.5" type="email" placeholder="Your email" />
                    <button className="p-1.5 bg-green-700 text-white">Subscribe</button>
                  </div>
                  <div className="flex justify-between w-2/4 space-x-4">
                    {[FaFacebookF, FaTwitter, FaInstagram, FaLinkedin, FaYoutube].map((Icon, index) => (
                      <span key={index} className="bg-green-700 p-2.5 rounded-full flex justify-center items-center">
                        {React.createElement(Icon, { className: "text-white" })}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </section>

            <footer className="w-full h-60 bg-gray-700 flex items-end justify-center">
              <div className="w-4/5 h-4/5 flex flex-col justify-between items-center">
                <div className="w-full h-2/4 border-b border-gray-300 flex">
                  {[
                    { icon: IoLayers, title: "Book Information?", description: "Please send us an email at support@gmail.com" },
                    { icon: FaLifeRing, title: "Need Help?", description: "Please contact our support team." }
                  ].map(({ icon: Icon, title, description }, index) => (
                    <div key={index} className="w-2/4 h-full flex">
                      <div className="h-3/4 flex items-center">
                        <Icon className="w-3/4 h-3/4 text-green-700" />
                      </div>
                      <div className="text-white flex flex-col gap-0.5 pt-2">
                        <h3>{title}</h3>
                        <p>{description}</p>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="w-full h-2/4 flex items-center justify-between">
                  <h1 className="text-white text-2xl w-2/4 h-3/4 flex items-center">BookShelf</h1>
                  <p className="text-white inline-flex items-center space-x-1 w-2/4 h-3/4 flex items-center justify-end">
                    <FaRegCopyright />
                    <span>2025 all rights reserved</span>
                  </p>
                </div>
              </div>
            </footer>
          </FavoritesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
